---
title: "Effective digital note taking: How to organize your knowledge and streamline your workflow"
---

## Description:

Effective note-taking is an important skill for any scientist to keep track of their tasks and projects, key learnings from papers, and new ideas. In this interactive workshop, we will explore digital note-taking and I will introduce the powerful markdown-based note-taking tool Obsidian. It allows you to keep all your notes interconnected, organized and easy to find and it is highly flexibel and can be adapted to your specific needs. For me, this tool was a real game-changer and I wished I had known it before I started my PhD. 

## Material

- [Markdown reference](markdown-reference.qmd)
- [Hands-on 1: Create your first Obsidian vault](task1-create-vault.qmd)
- [Hands-on 2: Work with the demo notebook](task2-demo-notebook.qmd): Demo vault

You can find most of the workshop content also explained in this video from my 
scientific workflows lecture series:

{{< video https://youtu.be/WPAV1SNkdFg?si=U5EWwFa5ji9UF6fJ >}}

## Contact

For any questions or feedback [send me an email](mailto:selina.baldauf@fu-berlin.de)

## Further resources

- Install Obsidian from [https://obsidian.md/](https://obsidian.md/)
- Get the Obsidian demo vault for academic notetaking from [Github](https://github.com/selinaZitrone/notebook_demo)
  - Read the README file for a step-by-step guide on how to download and open the vault in Obsidian
  - Have a look at the "Get Started" files in the demo vault for explanations and step-by-step guides
- A good [tutorial video for Obsidian beginners](https://www.youtube.com/embed/OUrOfIqvGS4)
- [Obsidian plugin recommendations 1](https://www.youtube.com/embed/2zhnb9KwmtA?si=Pf-Z3Y76ghBW0xo7)
- [Obsidian plugin recommendations 2](https://www.youtube.com/embed/cBm95iCcX2E?si=uPCKGg32Q2V1AXvx)

- [Step-by-Step guide](https://elizabethbutlermd.com/obsidian-notes/) on how to get started with Obsidian in written form
- [Blogpost: Note Taking System For Success in Academia](https://ilyashabanov.substack.com/p/note-taking-system-for-success-in) using Obsidian


